name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  DIRECTUS_API_KEY: ${{ secrets.DIRECTUS_API_KEY }}

jobs:
  run-build:
    name: Build Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd site && npm i
      - run: cd site && npm run build
      - name: Sync to FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER_CANADA }}
          user: ${{ secrets.FTP_USER_CANADA }}
          password: ${{ secrets.FTP_PW_CANADA }}
          local_dir: "./site/dist"
      - uses: jsmrcaga/action-netlify-deploy@v2
        name: Deploy to Netlify
        working-directory: site/dist
        install_command: "echo Skipping installing the dependencies"
        build_command: "echo Skipping building the web files"
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}