name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  DIRECTUS_API_KEY: ${{ secrets.DIRECTUS_API_KEY }}

jobs:
  run-build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
  run-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
      - name: Deploy
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER_CANADA }}
          user: ${{ secrets.FTP_USER_CANADA }}
          password: ${{ secrets.FTP_PW_CANADA }}