name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  DIRECTUS_API_KEY: ${{ secrets.DIRECTUS_API_KEY }}

jobs:
  run-build:
    uses: ./.github/workflows/build.yaml
    name: Build
    secrets: inherit
    with:
      artifact-name: build-output
  run-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    needs: run-build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.run-build.outputs.ARTIFACT_NAME }}
          path: ./
      - name: Test
        run: |
          ls -la
      # - name: Deploy
      #   uses: airvzxf/ftp-deployment-action@latest
      #   with:
      #     server: ${{ secrets.FTP_SERVER_CANADA }}
      #     user: ${{ secrets.FTP_USER_CANADA }}
      #     password: ${{ secrets.FTP_PW_CANADA }}