name: Deploy to Netlify

on: ["push"]

env:
  DIRECTUS_API_KEY: ${{ secrets.DIRECTUS_API_KEY }}

jobs:
  run-build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  run-deploy:
    needs: run-build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.2.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub action"
          NETLIFY_DEPLOY_TO_PROD: true
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"