name: PR Builds

on:
  pull_request:
    branches:
      - main

env:
  DIRECTUS_API_KEY: ${{ secrets.DIRECTUS_API_KEY }}

jobs:
  run-build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      artifact-name: build-output