name: Build and Deploy

on: ["push"]

env:
  DIRECTUS_API_KEY: ${{ secrets.DIRECTUS_API_KEY }}

jobs:
  run-build:
    name: Build
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      artifact-name: build-output
  run-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    needs: run-build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.run-build.outputs.artifact-name }}
          path: ./
      - name: Listing
        run: ls -la